### ISSUE TITLE
Error in Test and Build Artiset

### ISSUE THREAD

**Issue by jeslev** [alontalmor/LeapOfThought#1]
Hello Alon, first of all thanks for sharing your code with the community. While trying to run:

`pytest tests`

I'm getting the following error (I reduced the original output) :

	tests/artisets/soft_reasoning/counting_test.py:38: 
	 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
	LeapOfThought/artisets/soft_reasoning/counting.py:253: in build_artificial_dataset
		examples = self.building_balanced_counting_examples(counted_instances, false_statements, split)
	LeapOfThought/artisets/soft_reasoning/counting.py:170: in building_balanced_counting_examples
		for ci in all_counted_instaces])
	LeapOfThought/artisets/soft_reasoning/counting.py:170: in <listcomp>
		for ci in all_counted_instaces])
	/jlovon/miniconda3/envs/multiqa/lib/python3.7/site-packages/pandas/core/indexing.py:894: in __getitem__
		return self._getitem_axis(maybe_callable, axis=axis)
	/jlovon/miniconda3/envs/multiqa/lib/python3.7/site-packages/pandas/core/indexing.py:1500: in _getitem_ax
	is
		self._validate_integer(key, axis)
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

	self = <pandas.core.indexing._iLocIndexer object at 0x7f9f5aa5a770>, key = 0
	axis = 0

		def _validate_integer(self, key: int, axis: int) -> None:
			"""
			Check that 'key' is a valid position in the desired axis.
		
			Parameters
			----------
			key : int
				Requested position.
			axis : int
				Desired axis.
		
			Raises
			------
			IndexError
				If 'key' is not a valid position in axis 'axis'.
			"""
			len_axis = len(self.obj._get_axis(axis))
			if key >= len_axis or key < -len_axis:
	>           raise IndexError("single positional indexer is out-of-bounds")
	E           IndexError: single positional indexer is out-of-bounds

	/jlovon/miniconda3/envs/multiqa/lib/python3.7/site-packages/pandas/core/indexing.py:1443: IndexError

Ignoring this test, I tried to recreate the hypernyms training data with 
`python LeapOfThought/run.py -c Hypernyms -o build_artificial_dataset -out s3://aigame/data/taxonomic_reasonings/taxonomic_reasonings.jsonl.gz -v trainin_mix`

And I got:

	Traceback (most recent call last):
	  File "LeapOfThought/run.py", line 66, in <module>
		main()
	  File "LeapOfThought/run.py", line 56, in main
		artiset = ArtisetFactory().get_artiset(args.artiset_name, args)
	  File "/jlovon/LeapOfThought/LeapOfThought/artiset_factory.py", line 52, in get_artiset
		return getattr(mod, artiset_name)(args)
	AttributeError: module 'LeapOfThought.artisets.soft_reasoning.hypernyms' has no attribute 'Hypernyms'

Am I missing something?
Thanks

**Comment by jeslev** [comment]
Solved with running with a clean project. Apparently, after creating the artiset Hypernyms it did not rename the class name in the file.
